baseURL = 'https://skriverier.jehaj.dk/'
languageCode = 'da-DK'
title = 'Mine Skriverier'
defaultContentLanguage = 'dk'

[languages]
  [languages.dk]
    languageCode = 'da-DK'
    languageName = 'Dansk'
  [languages.en]
    languageCode = 'en-GB'
    languageName = 'English'
  

[[menus.main]]
name = 'Hjem'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Indl√¶g'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.highlight]
    style = 'github'