baseURL = 'https://skriverier.jehaj.dk/'
languageCode = 'da-DK'
title = 'Mine Skriverier'

[[menus.main]]
name = 'Hjem'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Indl√¶g'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
